export const eventTypes = [
  // Trip lifecycle
  "TRIP_PLANNED",
  "TRIP_STARTED",
  "TRIP_ENDED",
  "TRIP_CANCELLED",
  "TRIP_RETURN_PLAN_SET",
  "TRIP_RETURN_PLAN_ESCALATED",
  "TRIP_NOTE_ADDED",
  "TRIP_OWNER_TRANSFERRED",

  // Safety
  "SAFETY_BRIEFING_COMPLETED",
  "SAFETY_PROMPT_ACKED",
  "SAFETY_PLAYBOOK_TRIGGERED",
  "NEAR_MISS_RECORDED",
  "INCIDENT_OPENED",
  "INCIDENT_UPDATED",
  "INCIDENT_CLOSED",
  "STOP_WORK_TRIGGERED",
  "STOP_WORK_CLEARED",
  "MOB_WORKFLOW_STARTED",
  "MOB_WORKFLOW_COMPLETED",
  "SHELTER_HEATER_FLAGGED",
  "SHELTER_CO_REMINDER_ACKED",

  // Offshore gear lifecycle
  "GEAR_REGISTERED",
  "GEAR_SET",
  "GEAR_CHECKED",
  "GEAR_HAULED",
  "GEAR_MARKED_MISSING",
  "GEAR_RECOVERED",
  "GEAR_REMOVED",
  "GEAR_SWEEP_BLOCKED",
  "GEAR_SWEEP_CONFIRMED",
  "GEAR_RECOVERY_PLAN_CREATED",
  "GEAR_RECOVERY_PLAN_COMPLETED",
  "STRING_STORM_PRIORITY_SET",

  // Ice stations + tip-ups
  "STATION_CREATED",
  "STATION_UPDATED",
  "STATION_REMOVED",
  "TIPUP_SET",
  "TIPUP_CHECKED",
  "TIPUP_REBAITED",
  "TIPUP_REMOVED",
  "TIPUP_OVERDUE_FLAGGED",
  "ICE_SWEEP_CONFIRMED",

  // Activity cycles
  "ACTIVITY_CYCLE_STARTED",
  "ACTIVITY_CYCLE_COMPLETED",
  "ACTIVITY_CYCLE_ABORTED",
  "HAUL_CYCLE_STARTED",
  "HAUL_CYCLE_COMPLETED",
  "STATION_CYCLE_STARTED",
  "STATION_CYCLE_COMPLETED",

  // Catch + quality
  "CATCH_RECORDED",
  "CATCH_CORRECTED",
  "CATCH_RELEASE_REASON_ADDED",
  "CATCH_MEASUREMENT_ATTACHED",
  "CATCH_PHOTO_ATTACHED",
  "CATCH_QA_FLAGGED",
  "CATCH_QA_RESOLVED",

  // Compliance
  "COMPLIANCE_DRAFT_UPDATED",
  "COMPLIANCE_VALIDATION_RAN",
  "COMPLIANCE_SIGNED",
  "COMPLIANCE_FIELD_CORRECTED",
  "COMPLIANCE_AMENDMENT_ISSUED",

  // Trace + lots
  "LOT_CREATED",
  "LOT_UPDATED",
  "LOT_SCAN_ATTACHED",
  "LOT_SCAN_MISMATCH_FLAGGED",
  "LOT_SCAN_MISMATCH_RESOLVED",
  "LOT_CERTIFICATE_ISSUED",
  "LOT_CERTIFICATE_REVOKED",

  // Hazards + mapping
  "HAZARD_REPORTED",
  "HAZARD_CONFIRMED",
  "HAZARD_SCOPE_CHANGED",
  "HAZARD_ARCHIVED",
  "ICE_THICKNESS_LOGGED",
  "ROUTE_POINT_LOGGED",

  // Check-ins
  "CHECKIN_SCHEDULED",
  "CHECKIN_COMPLETED",
  "CHECKIN_MISSED",
  "CHECKIN_ESCALATED",
  "CHECKIN_ESCALATION_CLEARED",

  // Training
  "TRAINING_ASSIGNED",
  "TRAINING_STARTED",
  "TRAINING_COMPLETED",
  "TRAINING_OVERDUE",
  "TOOLBOX_TALK_PUBLISHED",
  "TOOLBOX_TALK_ACKED",

  // Rules + policy + export
  "RULESET_EFFECTIVE",
  "RISK_POLICY_APPLIED",
  "EXPORT_GENERATED",
  "EXPORT_DELIVERED",
  "EXPORT_VERIFICATION_FAILED",

  // Sync/infra diagnostics
  "SYNC_VALIDATION_REJECTED",
  "SYNC_CURSOR_ADVANCED",
  "STL_BATCH_UPLOADED",
  "DEVICE_REGISTERED",
  "DEVICE_REVOKED",
  "DEVICE_KEY_ROTATED",

  // Reserved extension slots
  "ORG_MEMBER_INVITED",
  "ORG_MEMBER_ROLE_CHANGED",
  "PROCESSOR_REVIEW_STARTED",
  "PROCESSOR_REVIEW_COMPLETED",
  "TOURNAMENT_SUBMISSION_CREATED",
  "TOURNAMENT_SUBMISSION_VERIFIED",
  "TOURNAMENT_SUBMISSION_REJECTED"
] as const;

export type EventType = (typeof eventTypes)[number];
